<<<<<<< HEAD
# Generated by Django 4.2.7 on 2026-04-16 09:49
=======
# Generated by Django 4.2.7 on 2026-04-16 10:09
>>>>>>> assignment/fix-stored-xss-profile-content

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
                ('bio', models.TextField(blank=True)),
>>>>>>> assignment/fix-stored-xss-profile-content
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
